spring:
  application:
    name: api-gateway
  main:
    web-application-type: reactive
  cloud:
    gateway:
      routes:
        - id: client-service
          uri: http://localhost:8081
          predicates:
            - Path=/client-service/**
          filters:
            - StripPrefix=1

server:
  port: 8080

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: https://discovery-service-1s4c.onrender.com/eureka/

jwt:
  secret: g7Dxm4ZK6BvNUdYp0nXcW93RflsQEp1M2jhVAGuqSyLktFeiH3oTazJYCNbPXrwL
  expiration: 86400000
