spring:
  # ==========================
  #  DATASOURCE
  # ==========================
  datasource:
    url: jdbc:postgresql://ep-misty-hill-a15ws4qr-pooler.ap-southeast-1.aws.neon.tech:5432/clien-service?sslmode=require
    username: neondb_owner
    password: npg_6ROBVwsIM7HA
    driver-class-name: org.postgresql.Driver

  # ==========================
  #  JPA / HIBERNATE
  # ==========================
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  # ==========================
  #  REDIS / CACHE
  # ==========================
  data:
    redis:
      host: redis-11733.c295.ap-southeast-1-1.ec2.redns.redis-cloud.com
      port: 11733
      password: iLBgYsHKj8uup4w0O9d682cgh1xvwIuu
      timeout: 60000
  cache:
    type: redis

  # ==========================
  #  SECURITY / OAUTH2
  # ==========================
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 449571709726-3kkvqdsfa4tvdb7rlv94k081v301s33q.apps.googleusercontent.com
            client-secret: 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
            scope: email, profile
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            client-name: Google
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            user-name-attribute: sub

  application:
    name: client-service

  cloud:
    discovery:
      enabled: true
    loadbalancer:
      enabled: true
    config:
      enabled: false

# ==========================
#  SERVER CONFIG
# ==========================
server:
  port: 8081
  ssl:
    enabled: false

# ==========================
#  JWT CONFIG
# ==========================
jwt:
  private-key-path: classpath:ssl/jwt-private.pem
  public-key-path: classpath:ssl/jwt-public.pem
  access-expiration: 900000
  refresh-expiration: 604800000

# ==========================
#  CLOUDINARY CONFIG
# ==========================
cloudinary:
  cloud-name: dpvtwky0z
  api-key: 538195674449633
  api-secret: HNyJYMzWwVYMjE_K2dIdsbAX7Wg

# ==========================
#  MAIL CONFIG
# ==========================
mail:
  username: chihwuwhulight@gmail.com
  password: vjsg vwim snyf bfyo

# ==========================
#  LOGGING
# ==========================
logging:
  level:
    org.springframework.security: DEBUG
